// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sns.Domains.Entities
{
    /// <summary>
    /// 用户表
    /// </summary>
    public partial class Account
    {
        public int Id { get; set; }
        /// <summary>
        /// 账号
        /// </summary>
        public string Account1 { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string Pwd { get; set; }
        /// <summary>
        /// 昵称，最大八个汉字
        /// </summary>
        public string NickName { get; set; }
        /// <summary>
        /// 头像路径
        /// </summary>
        public string Avatar { get; set; }
        /// <summary>
        /// 一句话介绍，最大150个中文，中文占3长度
        /// </summary>
        public string Intro { get; set; }
        public DateTime CreateTime { get; set; }
    }
}