// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sns.Domains.Entities
{
    /// <summary>
    /// 文章内容表
    /// </summary>
    public partial class ArticleContent
    {
        public int Id { get; set; }
        /// <summary>
        /// 文章ID
        /// </summary>
        public int ArticleId { get; set; }
        /// <summary>
        /// 内容体3000个字符长度
        /// </summary>
        public string Body { get; set; }
    }
}