// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sns.Domains.Entities
{
    /// <summary>
    /// 文章表
    /// </summary>
    public partial class Article
    {
        public int Id { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public int AccountId { get; set; }
        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 内容类型 1：文章
        /// </summary>
        public int ContentType { get; set; }
        /// <summary>
        /// 阅读数
        /// </summary>
        public int ViewCount { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
    }
}