// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sns.Domains.Entities
{
    /// <summary>
    /// 评论赞表
    /// </summary>
    public partial class CommentThumb
    {
        public int Id { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public int AccountId { get; set; }
        /// <summary>
        /// 评论ID
        /// </summary>
        public int CommentId { get; set; }
        public DateTime CreateTime { get; set; }
    }
}