// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sns.Domains.Entities
{
    /// <summary>
    /// 反馈表
    /// </summary>
    public partial class Feedback
    {
        public int Id { get; set; }
        /// <summary>
        /// 名字
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 联系方式
        /// </summary>
        public string Contact { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        public string Content { get; set; }
        public DateTime CreateTime { get; set; }
    }
}