// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sns.Domains.Entities
{
    /// <summary>
    /// 关注表
    /// </summary>
    public partial class Follow
    {
        public int Id { get; set; }
        /// <summary>
        /// 关注者ID
        /// </summary>
        public int AccountId { get; set; }
        /// <summary>
        /// 被关注ID
        /// </summary>
        public int FollowId { get; set; }
        public DateTime CreateTime { get; set; }
    }
}