// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class AccountConfiguration : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> entity)
        {
            entity.ToTable("account");

            entity.HasComment("用户表");

            entity.HasIndex(e => e.Account1)
                .HasName("Account")
                .IsUnique();

            entity.Property(e => e.Account1)
                .IsRequired()
                .HasColumnName("Account")
                .HasColumnType("varchar(20)")
                .HasComment("账号")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.Avatar)
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasComment("头像路径")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.Property(e => e.Intro)
                .IsRequired()
                .HasColumnType("varchar(200)")
                .HasComment("一句话介绍，最大150个中文，中文占3长度")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.NickName)
                .IsRequired()
                .HasColumnType("varchar(30)")
                .HasComment("昵称，最大八个汉字")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.Pwd)
                .IsRequired()
                .HasColumnType("varchar(50)")
                .HasComment("密码")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Account> entity);
    }
}
