// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class ArticleConfiguration : IEntityTypeConfiguration<Article>
    {
        public void Configure(EntityTypeBuilder<Article> entity)
        {
            entity.ToTable("article");

            entity.HasComment("文章表");

            entity.HasIndex(e => e.AccountId)
                .HasName("IDX_Article_AccountId");

            entity.HasIndex(e => e.ContentType)
                .HasName("IDX_Article_ContentType");

            entity.Property(e => e.AccountId).HasComment("用户ID");

            entity.Property(e => e.ContentType).HasComment("内容类型 1：文章");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.Property(e => e.LastUpdateTime).HasColumnType("datetime");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnType("varchar(100)")
                .HasComment("标题")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.ViewCount).HasComment("阅读数");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Article> entity);
    }
}
