// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class ArticleTopicConfiguration : IEntityTypeConfiguration<ArticleTopic>
    {
        public void Configure(EntityTypeBuilder<ArticleTopic> entity)
        {
            entity.ToTable("article_topic");

            entity.HasIndex(e => e.TopicId)
                .HasName("IDX_ArticleTopic_TopicId");

            entity.HasIndex(e => new { e.ArticleId, e.TopicId })
                .HasName("UK_ArticleId_TopicId")
                .IsUnique();

            entity.Property(e => e.ArticleId).HasComment("文章ID");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.Property(e => e.TopicId).HasComment("话题ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArticleTopic> entity);
    }
}
