// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class ArticleContentConfiguration : IEntityTypeConfiguration<ArticleContent>
    {
        public void Configure(EntityTypeBuilder<ArticleContent> entity)
        {
            entity.ToTable("article_content");

            entity.HasComment("文章内容表");

            entity.HasIndex(e => e.ArticleId)
                .HasName("IDK_Content_ArticleId");

            entity.Property(e => e.ArticleId).HasComment("文章ID");

            entity.Property(e => e.Body)
                .IsRequired()
                .HasColumnType("varchar(3000)")
                .HasComment("内容体3000个字符长度")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArticleContent> entity);
    }
}
