// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class CommentConfiguration : IEntityTypeConfiguration<Comment>
    {
        public void Configure(EntityTypeBuilder<Comment> entity)
        {
            entity.ToTable("comment");

            entity.HasComment("评论表");

            entity.HasIndex(e => e.ArticleId)
                .HasName("IDX_Comment_ArticleId");

            entity.HasIndex(e => new { e.AccountId, e.ArticleId })
                .HasName("IDX_Comment_AccountId_ArticleId");

            entity.Property(e => e.AccountId).HasComment("用户ID");

            entity.Property(e => e.ArticleId).HasComment("文章ID");

            entity.Property(e => e.Body)
                .IsRequired()
                .HasColumnType("varchar(500)")
                .HasComment("评论内容")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.Property(e => e.QuoteId).HasComment("引用ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Comment> entity);
    }
}
