// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class FavoriteConfiguration : IEntityTypeConfiguration<Favorite>
    {
        public void Configure(EntityTypeBuilder<Favorite> entity)
        {
            entity.ToTable("favorite");

            entity.HasComment("收藏表");

            entity.HasIndex(e => new { e.AccountId, e.ArticleId })
                .HasName("UK_Favorite_AccountId_ArticleId")
                .IsUnique();

            entity.Property(e => e.AccountId).HasComment("用户ID");

            entity.Property(e => e.ArticleId).HasComment("文章ID");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Favorite> entity);
    }
}
