// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class FeedbackConfiguration : IEntityTypeConfiguration<Feedback>
    {
        public void Configure(EntityTypeBuilder<Feedback> entity)
        {
            entity.ToTable("feedback");

            entity.HasComment("反馈表");

            entity.Property(e => e.Contact)
                .IsRequired()
                .HasColumnType("varchar(30)")
                .HasComment("联系方式")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnType("varchar(300)")
                .HasComment("内容")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("varchar(10)")
                .HasComment("名字")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Feedback> entity);
    }
}
