// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class FollowConfiguration : IEntityTypeConfiguration<Follow>
    {
        public void Configure(EntityTypeBuilder<Follow> entity)
        {
            entity.ToTable("follow");

            entity.HasComment("关注表");

            entity.HasIndex(e => new { e.AccountId, e.FollowId })
                .HasName("UK_Follow_AccountId_FollowId")
                .IsUnique();

            entity.Property(e => e.AccountId).HasComment("关注者ID");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.Property(e => e.FollowId).HasComment("被关注ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Follow> entity);
    }
}
