// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Sns.Domains.Entities;
using System;

#nullable disable

namespace Sns.Domains.Entities.Configurations
{
    public partial class TopicConfiguration : IEntityTypeConfiguration<Topic>
    {
        public void Configure(EntityTypeBuilder<Topic> entity)
        {
            entity.ToTable("topic");

            entity.HasComment("话题表");

            entity.HasIndex(e => e.Name)
                .HasName("UK_Topic_Name")
                .IsUnique();

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("varchar(50)")
                .HasComment("名称")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Topic> entity);
    }
}
